### ISSUE TITLE
Update to auto-resample.bat

### ISSUE THREAD

**Issue by TheJman494** [emoose/re4-research#2]
In the current release there is no `""` around `%%X`, meaning it will fail with spaces in the path. Considering the base game has spaces "Resident Evil 4" it wouldn't work out of the box.

Here is a fixed auto-resample.bat:
```
@echo off
REM make sure ffmpeg.exe is somewhere this .bat can access (eg. next to the .bat, or on your %PATH%)
FOR /r %%X IN (*.xwb) DO (
  re4resample.exe -r 48000 -l "%%X"
)
pause
```

**Comment by emoose** [comment]
Oh good catch, will update that now.

E: pushed a new zip with fixed bat file.
